# Import libararies

In [1]:
import pandas as pd
import numpy as np
import matplotlib as lib
import seaborn as sns
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn import preprocessing
from sklearn.compose import ColumnTransformer

# Read files

In [111]:
data = pd.read_csv("house_price_train.csv")
data2= pd.read_csv("house_price_train.csv")
data3=pd.read_csv("house_price_train.csv")
test = pd.read_csv("house_price_test.csv")

print(len(test.columns))
print(len(data.columns))
print(test.shape)
print(data.shape)

80
81
(1459, 80)
(1460, 81)

In [3]:
data.head(10)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900
9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2008,WD,Normal,118000

# information

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [5]:
data.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [6]:
data.shape

(1460, 81)

In [7]:
len(data)

1460

# cleaning data

In [114]:


print(len(test.columns))
print(len(data.columns))
print(test.shape)
print(data.shape)

80
81
(1459, 80)
(1460, 81)

In [9]:
na_percentage = data.isna().mean() * 100

# Drop columns with NaN percentage greater than 70%
columns_to_drop = na_percentage[na_percentage > 11].index
new_data = data.drop(columns_to_drop, axis=1,inplace=True)

## drop duplicates

In [10]:
df_t1= data.T
df_t2= data2.T

In [11]:
df_t1.drop_duplicates()
df_t2.drop_duplicates()# in column

,0,1,2,3,4,5,6,7,8,9,...,1450,1451,1452,1453,1454,1455,1456,1457,1458,1459
Id,1,2,3,4,5,6,7,8,9,10,...,1451,1452,1453,1454,1455,1456,1457,1458,1459,1460
MSSubClass,60,20,60,70,60,50,20,60,50,190,...,90,20,180,20,20,60,20,70,20,20
MSZoning,RL,RL,RL,RL,RL,RL,RL,RL,RM,RL,...,RL,RL,RM,RL,FV,RL,RL,RL,RL,RL
LotArea,8450,9600,11250,9550,14260,14115,10084,10382,6120,7420,...,9000,9262,3675,17217,7500,7917,13175,9042,9717,9937
Street,Pave,Pave,Pave,Pave,Pave,Pave,Pave,Pave,Pave,Pave,...,Pave,Pave,Pave,Pave,Pave,Pave,Pave,Pave,Pave,Pave
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MoSold,2,5,9,2,12,10,8,11,4,1,...,9,5,5,7,10,8,2,5,4,6
YrSold,2008,2007,2008,2006,2008,2009,2007,2009,2008,2008,...,2009,2009,2006,2006,2009,2007,2010,2010,2010,2008
SaleType,WD,WD,WD,WD,WD,WD,WD,WD,WD,WD,...,WD,New,WD,WD,WD,WD,WD,WD,WD,WD
SaleCondition,Normal,Normal,Normal,Abnorml,Normal,Normal,Normal,Normal,Abnorml,Normal,...,Normal,Partial,Normal,Abnorml,Normal,Normal,Normal,Normal,Normal,Normal
SalePrice,208500,181500,223500,140000,250000,143000,307000,200000,129900,118000,...,136000,287090,145000,84500,185000,175000,210000,266500,142125,147500

In [12]:
data=df_t1.T # data after drop duplicates
data2=df_t2.T
data3=data2

## fill nan value

In [150]:
numerical_columns = data.select_dtypes(include=[np.number])
data[numerical_columns.columns] = numerical_columns.fillna(0)

numerical_columns = test.select_dtypes(include=[np.number])
test[numerical_columns.columns] = numerical_columns.fillna(0)

numerical_columns = data2.select_dtypes(include=[np.number])
data2[numerical_columns.columns] = numerical_columns.fillna(0)
data2.isna().any().sum()

0

In [142]:
categorical_columns = data.select_dtypes(include=['object'])
data[categorical_columns.columns] = categorical_columns.fillna('Unknown')
categorical_columns = test.select_dtypes(include=['object'])
test[categorical_columns.columns] = categorical_columns.fillna('Unknown')
categorical_columns = data2.select_dtypes(include=['object'])
data2[categorical_columns.columns] = categorical_columns.fillna('Unknown')

In [115]:
data.isna().sum()

Id               0
MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
                ..
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
SalePrice        0
Length: 81, dtype: int64

In [116]:
test.isna().sum()

Id               0
MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
                ..
MiscVal          0
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
Length: 80, dtype: int64

## data after cleaning

In [117]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1460 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          1460 non-null   object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1460 non-null   object
 26  MasVnrArea     1460 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1460 non-null   object
 31  BsmtCond       1460 non-null   object
 32  BsmtExposure   1460 non-null   object
 33  BsmtFinType1   1460 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1460 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1460 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    1460 non-null   object
 58  GarageType     1460 non-null   object
 59  GarageYrBlt    1460 non-null   float64
 60  GarageFinish   1460 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1460 non-null   object
 64  GarageCond     1460 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         1460 non-null   object
 73  Fence          1460 non-null   object
 74  MiscFeature    1460 non-null   object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [134]:
cate_columns = data.select_dtypes(include=['object'])

numerical_columns = data.select_dtypes(include=['int64','float64'])

cata_columns_list= list(cate_columns.columns)
numerical_columns_list = list(numerical_columns.columns)

In [119]:
cata_columns_list

['MSZoning',
 'Street',
 'Alley',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'SaleType',
 'SaleCondition']

In [120]:
numerical_columns_list

['Id',
 'MSSubClass',
 'LotFrontage',
 'LotArea',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'MasVnrArea',
 'BsmtFinSF1',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Fireplaces',
 'GarageYrBlt',
 'GarageCars',
 'GarageArea',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal',
 'MoSold',
 'YrSold',
 'SalePrice']

# one hot encoder

In [135]:
print(len(test.columns))
print(len(data.columns))
print(test.shape)
print(data.shape)

80
81
(1459, 80)
(1460, 81)

In [121]:
one_hot = OneHotEncoder()
transformer=ColumnTransformer([('one_hot',one_hot,cata_columns_list)],remainder='passthrough')

In [122]:
transform = transformer.fit_transform(data)

In [123]:
dummies=pd.get_dummies(data,columns=cata_columns_list)

In [137]:
transformer2=ColumnTransformer([('one_hot',one_hot,cata_columns_list)],remainder='passthrough')
# cata_test = list(test.select_dtypes('object').columns)
transform2 = transformer2.fit_transform(test)
dummies2=pd.get_dummies(test,columns=cata_columns_list)

In [138]:
print(len(dummies2.columns))
print(len(x_test.columns))

293
216

In [126]:
dummies= dummies

In [127]:
dummies.shape

(1460, 306)

In [24]:
dummies.dtypes

Id                       int64
MSSubClass               int64
LotArea                  int64
OverallQual              int64
OverallCond              int64
                         ...
SaleCondition_AdjLand    uint8
SaleCondition_Alloca     uint8
SaleCondition_Family     uint8
SaleCondition_Normal     uint8
SaleCondition_Partial    uint8
Length: 217, dtype: object

In [84]:
y=dummies['SalePrice']

In [83]:
x=dummies.drop('SalePrice',axis=1)

In [85]:
x_t = dummies2

## modeling after one hot

In [128]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [129]:
model= RandomForestRegressor()

In [130]:
model.fit(x_train,y_train)

RandomForestRegressor()

In [131]:
model.score(x_test,y_test)

0.8348804570596557

In [133]:
y_p = model.predict(x_t)

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- BldgType
- BsmtCond
- BsmtExposure
- BsmtFinType1
- BsmtFinType2
- ...
Feature names seen at fit time, yet now missing:
- BldgType_1Fam
- BldgType_2fmCon
- BldgType_Duplex
- BldgType_Twnhs
- BldgType_TwnhsE
- ...

In [32]:
y_test[:10]

1180    250000
289     153575
22      230000
840     140000
658      97500
210      98000
921     145900
796     143500
1091    160000
706     302000
Name: SalePrice, dtype: int64

## label encoder

In [151]:
print(len(test.columns))
print(len(data2.columns))
print(test.shape)
print(data2.shape)

80
81
(1459, 80)
(1460, 81)

In [152]:
label_encoder = preprocessing.LabelEncoder()
for column in data2.columns:
    # Check if the column contains categorical data
    if data2[column].dtype == 'object':
        # Fit the LabelEncoder on the column and transform the labels
        data2[column] = label_encoder.fit_transform(data[column])

In [145]:
label_encoder = preprocessing.LabelEncoder()
for column in test.columns:
    # Check if the column contains categorical data
    if test[column].dtype == 'object':
        # Fit the LabelEncoder on the column and transform the labels
        test[column] = label_encoder.fit_transform(test[column])

In [146]:
test

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,2,80.0,11622,1,2,3,3,0,...,120,0,2,2,3,0,6,2010,9,4
1,1462,20,3,81.0,14267,1,2,0,3,0,...,0,0,2,4,0,12500,6,2010,9,4
2,1463,60,3,74.0,13830,1,2,0,3,0,...,0,0,2,2,3,0,3,2010,9,4
3,1464,60,3,78.0,9978,1,2,0,3,0,...,0,0,2,4,3,0,6,2010,9,4
4,1465,120,3,43.0,5005,1,2,0,1,0,...,144,0,2,4,3,0,1,2010,9,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,4,21.0,1936,1,2,3,3,0,...,0,0,2,4,3,0,6,2006,9,4
1455,2916,160,4,21.0,1894,1,2,3,3,0,...,0,0,2,4,3,0,4,2006,9,0
1456,2917,20,3,160.0,20000,1,2,3,3,0,...,0,0,2,4,3,0,9,2006,9,0
1457,2918,85,3,62.0,10441,1,2,3,3,0,...,0,0,2,2,2,700,7,2006,9,4
1458,2919,60,3,74.0,9627,1,2,3,3,0,...,0,0,2,4,3,0,11,2006,9,4

In [34]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 62 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   int32
 3   LotArea        1460 non-null   int64
 4   Street         1460 non-null   int32
 5   LotShape       1460 non-null   int32
 6   LandContour    1460 non-null   int32
 7   Utilities      1460 non-null   int32
 8   LotConfig      1460 non-null   int32
 9   LandSlope      1460 non-null   int32
 10  Neighborhood   1460 non-null   int32
 11  Condition1     1460 non-null   int32
 12  Condition2     1460 non-null   int32
 13  BldgType       1460 non-null   int32
 14  HouseStyle     1460 non-null   int32
 15  OverallQual    1460 non-null   int64
 16  OverallCond    1460 non-null   int64
 17  YearBuilt      1460 non-null   int64
 18  YearRemodAdd   1460 non-null   int64
 19  RoofStyle      1460 non-null   int32
 20  RoofMatl       1460 non-null   int32
 21  Exterior1st    1460 non-null   int32
 22  Exterior2nd    1460 non-null   int32
 23  ExterQual      1460 non-null   int32
 24  ExterCond      1460 non-null   int32
 25  Foundation     1460 non-null   int32
 26  BsmtFinSF1     1460 non-null   int64
 27  BsmtFinSF2     1460 non-null   int64
 28  BsmtUnfSF      1460 non-null   int64
 29  TotalBsmtSF    1460 non-null   int64
 30  Heating        1460 non-null   int32
 31  HeatingQC      1460 non-null   int32
 32  CentralAir     1460 non-null   int32
 33  1stFlrSF       1460 non-null   int64
 34  2ndFlrSF       1460 non-null   int64
 35  LowQualFinSF   1460 non-null   int64
 36  GrLivArea      1460 non-null   int64
 37  BsmtFullBath   1460 non-null   int64
 38  BsmtHalfBath   1460 non-null   int64
 39  FullBath       1460 non-null   int64
 40  HalfBath       1460 non-null   int64
 41  BedroomAbvGr   1460 non-null   int64
 42  KitchenAbvGr   1460 non-null   int64
 43  KitchenQual    1460 non-null   int32
 44  TotRmsAbvGrd   1460 non-null   int64
 45  Functional     1460 non-null   int32
 46  Fireplaces     1460 non-null   int64
 47  GarageCars     1460 non-null   int64
 48  GarageArea     1460 non-null   int64
 49  PavedDrive     1460 non-null   int32
 50  WoodDeckSF     1460 non-null   int64
 51  OpenPorchSF    1460 non-null   int64
 52  EnclosedPorch  1460 non-null   int64
 53  3SsnPorch      1460 non-null   int64
 54  ScreenPorch    1460 non-null   int64
 55  PoolArea       1460 non-null   int64
 56  MiscVal        1460 non-null   int64
 57  MoSold         1460 non-null   int64
 58  YrSold         1460 non-null   int64
 59  SaleType       1460 non-null   int32
 60  SaleCondition  1460 non-null   int32
 61  SalePrice      1460 non-null   int64
dtypes: int32(27), int64(35)
memory usage: 553.3 KB

## modeling label encoder

In [153]:
x2=data2.drop('SalePrice',axis=1)
y2=data2['SalePrice']
x_train2,x_test2,y_train2,y_test2 = train_test_split(x2,y2,test_size=0.2)

In [154]:
model.fit(x_train2,y_train2)

RandomForestRegressor()

In [37]:
model.score(x_test2,y_test2)

0.9093783554791137

In [155]:
y_p = model.predict(test)

In [156]:
sub = pd.read_csv("sample_submission.csv")
sub

        Id      SalePrice
0     1461  169277.052498
1     1462  187758.393989
2     1463  183583.683570
3     1464  179317.477511
4     1465  150730.079977
...    ...            ...
1454  2915  167081.220949
1455  2916  164788.778231
1456  2917  219222.423400
1457  2918  184924.279659
1458  2919  187741.866657

[1459 rows x 2 columns]

In [158]:
test_ids = sub['Id']
submission_preds=y_p
output = pd.DataFrame({"Id":test_ids.values,"SalePrice":submission_preds})
output.to_csv(f'model_ensemble_v1_submission.csv', index=False)

In [38]:
np.random.seed()
for i in range(10,101,10):
    print('n_estamator: ',i)
    model2=RandomForestRegressor(n_estimators=i).fit(x_train2,y_train2)
    print(f'model accuracy on test:{model2.score(x_test2,y_test2)*100:0.2f} ','%')
    print(' ')

n_estamator:  10
model accuracy on test:89.56  %

n_estamator:  20
model accuracy on test:90.52  %

n_estamator:  30
model accuracy on test:90.75  %

n_estamator:  40
model accuracy on test:91.03  %

n_estamator:  50
model accuracy on test:90.52  %

n_estamator:  60
model accuracy on test:91.14  %

n_estamator:  70
model accuracy on test:90.88  %

n_estamator:  80
model accuracy on test:90.91  %

n_estamator:  90
model accuracy on test:91.04  %

n_estamator:  100
model accuracy on test:90.67  %

In [39]:
data3.head()

,Id,MSSubClass,MSZoning,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,0,5,3,327,1,3,3,0,4,0,...,0,0,0,0,0,1,2,8,4,412
1,1,0,3,498,1,3,3,0,2,0,...,0,0,0,0,0,4,1,8,4,339
2,2,5,3,702,1,0,3,0,4,0,...,0,0,0,0,0,8,2,8,4,442
3,3,6,3,489,1,0,3,0,0,0,...,108,0,0,0,0,1,0,8,0,194
4,4,5,3,925,1,0,3,0,2,0,...,0,0,0,0,0,11,2,8,4,494

In [40]:
data3['SaleCondition'].unique()

array([4, 0, 5, 1, 2, 3])

In [41]:
x=data3['SaleCondition']
y=data3['SalePrice']
y

0       412
1       339
2       442
3       194
4       494
       ...
1455    314
1456    415
1457    527
1458    199
1459    221
Name: SalePrice, Length: 1460, dtype: int64

In [42]:
df = pd.DataFrame({'x':x,'y':y})

In [43]:
df

      x    y
0     4  412
1     4  339
2     4  442
3     0  194
4     4  494
...  ..  ...
1455  4  314
1456  4  415
1457  4  527
1458  4  199
1459  4  221

[1460 rows x 2 columns]

In [73]:
y_p = model.predict(x_test2)

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- Alley
- BsmtCond
- BsmtExposure
- BsmtFinType1
- BsmtFinType2
- ...

In [ ]:
t = test.drop(['id'],axis=1)

In [ ]:
sub["Hardness"]=model.predict(t)
sub.to_csv('submission.csv',index=False)

In [ ]:
test_ids = test['id']
submission_preds=model.predict(t)

In [ ]:
df = pd.DataFrame({"ID_LAT_LON_YEAR_WEEK":test_ids.values,"emission":submission_preds})

In [ ]:
df.to_csv('submission2.csv',index=False)

In [ ]:
sub["Hardness"]=model.predict(t)
sub.to_csv('submission.csv',index=False)